name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt

    - name: Install Node.js dependencies and fetch dataset
      run: make install

    - name: Run server
      run: make run &
      env:
        PORT: 3000

    - name: Wait for server to start
      run: sleep 10

    - name: Test server is running
      run: curl -I http://localhost:3000

    - name: Stop server
      run: kill $(lsof -t -i:3000) || true
