name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: make install

    - name: Run server
      run: make run &

    - name: Wait for server to start
      run: sleep 10

    - name: Test server is running
      run: curl -I http://localhost:3000

    - name: Stop server
      run: kill $(lsof -t -i:3000) || true